import { gql, useLazyQuery } from '@apollo/client'
import type { NextPage } from 'next'
import Link from 'next/link';
import Head from 'next/head'
import { useEffect, useMemo } from 'react'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/dist/client/router';

const GET_TODOS = gql`
fragment todoFields on Todo {
  id
  text
  complete
}

query Query($complete: Boolean) {
  todos(complete: $complete) {
    ...todoFields
  }
}
`;

const Home: NextPage = () => {
  const { query, isReady } = useRouter();
  const complete = useMemo(() => {
    switch (query.complete) {
      case 'active': return false;
      case 'complete': return true;
      default: return null;
    }
  }, [query.complete]);
  const [getTodos, { loading, error, data }] = useLazyQuery(GET_TODOS, { variables: { complete } });
  useEffect(() => {
    if (isReady) {
      getTodos({ variables: { complete } });
    }
  }, [getTodos, complete, isReady]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link replace href="/">
          All
        </Link>
        <Link replace href={'/active'}>
          Active
        </Link>
        <Link replace href={'/complete'}>
          Complete
        </Link>

        <ul>
          {data?.todos.map(todo => (
            <li key={todo.id}>
              <input type="checkbox" checked={todo.complete} onChange={() => {}} />
              {todo.text}
            </li>
          ))}
        </ul>
      </main>

    </div>
  )
}

export default Home
