import { gql, useMutation, useQuery } from '@apollo/client'
import type { NextPage } from 'next'
import Link from 'next/link';
import Head from 'next/head'
import { useMemo, useState } from 'react'
import { useRouter } from 'next/dist/client/router';
import { Container, Button, Link as MuiLink, Input, TextField } from '@material-ui/core'
import { makeStyles, createStyles } from '@material-ui/core/styles'

const useStyles = makeStyles(theme => createStyles({
  linkActive: {
    fontWeight: theme.typography.fontWeightBold,
  },
}));

const TODO_FIELDS = gql`
fragment todoFields on Todo {
  id
  text
  complete
}
`;

const GET_TODOS = gql`
${TODO_FIELDS}
query GetTodos($complete: Boolean) {
  todos(complete: $complete) {
    ...todoFields
  }
}
`;

const ADD_TODO = gql`
${TODO_FIELDS}
mutation AddTodo($input: TodoInput!) {
  addTodo(input: $input) {
    ...todoFields
  }
}
`;

const UPDATE_TODO = gql`
${TODO_FIELDS}
mutation UpdateTodo($id: ID!, $input: TodoInput!) {
  updateTodo(id: $id, input: $input) {
    ...todoFields
  }
}
`;

const DELETE_TODO = gql`
mutation DeleteTodo($id: ID!) {
  deleteTodo(id: $id)
}
`;

const Home: NextPage = () => {
  const classes = useStyles();
  const { query, asPath } = useRouter();
  const { loading, error, data } = useQuery(GET_TODOS);
  const [draftTodo, setDraftTodo] = useState('');

  const [addTodo, { loading: addingTodo }] = useMutation(ADD_TODO, {
    refetchQueries: [GET_TODOS],
  });

  const [updateTodo] = useMutation(UPDATE_TODO, {
    optimisticResponse: ({ id, input }) => ({ updateTodo: { id, ...input } }),
  });

  const [deleteTodo] = useMutation(DELETE_TODO, {
    optimisticResponse: ({ id }) => ({ deleteTodo: id }),
    update: (cache, { data: { deleteTodo } }) => {
      const { todos } = cache.readQuery({ query: GET_TODOS }) || { todos: [] };
      const todo = todos.find(x => x.id === deleteTodo);
      if (todo) {
        cache.evict({ id: cache.identify(todo) });
        cache.gc();
      }
    },
  });

  const filteredTodos = useMemo(() => {
    if (!data?.todos) { return []; }
    if (!query.complete) {
      return data.todos;
    }
    const complete = query.complete === 'complete';
    return data.todos.filter(x => x.complete === complete);
  }, [data, query.complete]);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link replace href="/" passHref>
          <MuiLink className={asPath === '/' ? classes.linkActive : ''}>
            All
          </MuiLink>
        </Link>
        <Link replace href={'/active'} passHref>
          <MuiLink className={asPath === '/active' ? classes.linkActive : ''}>
            Active
          </MuiLink>
        </Link>
        <Link replace href={'/complete'} passHref>
          <MuiLink className={asPath === '/complete' ? classes.linkActive : ''}>
            Complete
          </MuiLink>
        </Link>

        <form onSubmit={async e => {
          e.preventDefault();
          const { errors } = await addTodo({ variables: { input: { text: draftTodo, complete: false } } });
          if (!errors) {
            setDraftTodo('');
          }
        }}>
          <TextField
            label="Add todo"
            value={draftTodo}
            onChange={e => setDraftTodo(e.currentTarget.value)}
          />
          <Button type="submit" variant="contained" color="primary" disabled={addingTodo || draftTodo.trim() === ''}>
            Add
          </Button>
        </form>

        <ul>
          {filteredTodos.map(({ id, ...todo }) => (
            <li key={id}>
              <input type="checkbox" checked={todo.complete} onChange={() => {
                updateTodo({ variables: { id, input: { ...todo, complete: !todo.complete } } });
              }} />
              {todo.text}
              <Button onClick={() => deleteTodo({ variables: { id } })}>delete</Button>
            </li>
          ))}
        </ul>
      </main>

    </Container>
  )
}

export default Home
